# Tensors 

In [1]:
import torch

## zeros()

In [5]:
w=torch.zeros(3,4)

In [6]:
w

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## size() and shape

In [7]:
w.size()

torch.Size([3, 4])

In [10]:
w.shape

torch.Size([3, 4])

## randn() and randn_like()

In [12]:
w=torch.randn(4,3)
w

tensor([[-1.2555, -1.1089,  0.1895],
        [ 1.2926,  1.8043, -0.0650],
        [ 0.4858, -0.0639,  1.4438],
        [-1.1154,  0.7858, -1.8094]])

In [14]:
t=torch.rand_like(w)
t

tensor([[0.2285, 0.3803, 0.7732],
        [0.7272, 0.7965, 0.6596],
        [0.6329, 0.2654, 0.5361],
        [0.1524, 0.5893, 0.9092]])

## fill_()

In [15]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [16]:
w.view(6,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [19]:
type(w.numpy())

numpy.ndarray